import React, { useEffect, useState } from 'react';
import { FileText, Download, Plus, FileCode, FileSpreadsheet, RefreshCw } from 'lucide-react';
import { reportsService } from '../services/api';
import { SecurityReport } from '../types';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<SecurityReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [reportTitle, setReportTitle] = useState('CyberSentinel AI Executive Threat Assessment Report');
  const [format, setFormat] = useState<'PDF' | 'JSON' | 'CSV'>('PDF');
  const [generating, setGenerating] = useState(false);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await reportsService.listReports();
      setReports(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await reportsService.generateReport(reportTitle, format);
      fetchReports();
    } catch (e: any) {
      alert('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="border-b border-slate-800 pb-4">
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <FileText className="w-6 h-6 text-cyan-400" /> Automated Security Assessment Report Generator
        </h1>
        <p className="text-xs text-slate-400 mt-1">Generate executive security reports containing threat methodology, findings, evidence, and remediation steps in PDF, JSON, or CSV formats.</p>
      </div>

      {/* GENERATE REPORT WIZARD */}
      <div className="glass-card p-6 rounded-xl space-y-4">
        <h3 className="text-sm font-semibold text-white">Generate Security Assessment Report</h3>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="md:col-span-2">
            <label className="block text-xs font-semibold text-slate-300 mb-1">Report Title</label>
            <input
              type="text"
              value={reportTitle}
              onChange={(e) => setReportTitle(e.target.value)}
              className="w-full bg-[#0B0F17] border border-slate-800 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Output Format</label>
            <select
              value={format}
              onChange={(e) => setFormat(e.target.value as any)}
              className="w-full bg-[#0B0F17] border border-slate-800 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-500"
            >
              <option value="PDF">PDF (ReportLab Formatted)</option>
              <option value="JSON">JSON (Structured Data)</option>
              <option value="CSV">CSV (Tabular Data)</option>
            </select>
          </div>

          <div className="flex items-end">
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="w-full bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold py-2 px-4 rounded-lg text-xs flex items-center justify-center transition-all shadow-lg shadow-cyan-950"
            >
              {generating ? <RefreshCw className="w-4 h-4 animate-spin mr-2" /> : <Plus className="w-4 h-4 mr-2" />}
              Generate Report
            </button>
          </div>
        </div>
      </div>

      {/* REPORTS LIST */}
      <div className="glass-card p-5 rounded-xl space-y-4">
        <h3 className="text-sm font-semibold text-white">Generated Report Repository</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 font-medium">
                <th className="pb-3">Report UUID</th>
                <th className="pb-3">Title</th>
                <th className="pb-3">Format</th>
                <th className="pb-3">Total Findings</th>
                <th className="pb-3">Generated By</th>
                <th className="pb-3">Generated Date</th>
                <th className="pb-3">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-slate-200">
              {reports.map((rep) => (
                <tr key={rep.id} className="hover:bg-slate-800/30 transition-all">
                  <td className="py-3 font-mono text-cyan-400 font-bold">{rep.report_uuid}</td>
                  <td className="py-3 font-medium text-white">{rep.title}</td>
                  <td className="py-3 font-mono text-slate-300">{rep.format}</td>
                  <td className="py-3 text-slate-300">{rep.total_findings} ({rep.critical_count} Critical, {rep.high_count} High)</td>
                  <td className="py-3 text-slate-400">{rep.generated_by}</td>
                  <td className="py-3 text-slate-500">{rep.created_at ? new Date(rep.created_at).toLocaleString() : 'Just now'}</td>
                  <td className="py-3">
                    <a
                      href={reportsService.getDownloadUrl(rep.id)}
                      download
                      className="px-3 py-1 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 rounded font-semibold inline-flex items-center"
                    >
                      <Download className="w-3.5 h-3.5 mr-1" /> Download
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
